name: Kun.ai Build and Deploy to S3

on:
  push:
    paths:
      - 'kun-ai/**'
      - '.github/workflows/deploy-kun-ai.yml'
    branches:
      - main

  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - 'kun-ai/**'
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: kun-ai

    steps:
      - name: Checkout PR Branch
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './package-lock.json'

      - name: Install Dependencies
        run: npm ci

      - name: Create .env file
        run: touch .env

      - name: Build
        run: npm run build.all

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy Assets to S3
        run: aws s3 sync ./dist s3://${{ secrets.KUN_AI_BUCKET }} --exclude "index.html"
      - name: Deploy index.html with headers to S3
        run: aws s3 cp ./dist/index.html s3://${{ secrets.KUN_AI_BUCKET }}/index.html --cache-control "max-age=86400" --content-type "text/html"



      - name: Invalidate Entire CloudFront Cache for Main
        if: github.ref == 'refs/heads/main'
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.KUN_ID_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
